name: Build & Deploy to Pages

on:
  push:
    branches: [ master ]
  pull_request:
    types: closed
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages-react branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages-react
          folder: build

      - name: Push to Web3.storage
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: 'build'

      - run: echo ${{ steps.web3.outputs.cid }}
      - run: echo ${{ steps.web3.outputs.url }}
